{% set name = "pipenv" %}
{% set version = "2020.5.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81862314929e3e532502e25bab3c6ba969c0cf67dcaa9d63c2c931ee2d61541c

build:
  noarch: python
  number: 0
  entry_points:
    - pipenv=pipenv:cli
    - pewtwo=pipenv.patched.pew.pew:pew
    - pipenv-resolver=pipenv.resolver:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=9.0.1
    - python
  run:
    - certifi
    - pip >=9.0.1
    - python
    - setuptools >=36.2.1
    - virtualenv
    - virtualenv-clone >=0.2.5

test:
  imports:
    - pipenv

  commands:
    - pipenv --help

about:
  home: https://github.com/pypa/pipenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Development Workflow for Humans.
  doc_url: https://pipenv-fork.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - roccqqck
