{% set name = "pipenv" %}
{% set version = "2025.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pypa/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d7a481a3a97c954be21e3b4be48a0105fe24c8f02d90875ee026c80af122f9a0

build:
  number: 0
  entry_points:
    - pipenv=pipenv:cli
    - pipenv-resolver=pipenv.resolver:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=67
  run:
    - python
    - certifi
    - packaging >=22
    # setuptools is a part of run dependency https://github.com/pypa/pipenv/blob/v2025.0.4/pyproject.toml#L31
    - setuptools >=67
    - virtualenv >=20.24.2
  run_constrained:
    - safety >=3.0.0

test:
  source_files:
    - tests
    - pipenv
    - run-tests.sh
    - run-tests.bat
    - Pipfile
    - Pipfile.lock
    - pyproject.toml
  imports:
    - pipenv
    - pipenv.cli
    - pipenv.patched
    - pipenv.routines
    - pipenv.utils
    - pipenv.vendor
  requires:
    - pip
    - git
    - bash # [unix]
  commands:
    - python -c "import pipenv"
    - pipenv --help
    - pip check
    - PIPENV_PYTHON=3.9 bash run-tests.sh  # [unix and py39]
    - PIPENV_PYTHON=3.10 bash run-tests.sh # [unix and py310]
    - PIPENV_PYTHON=3.11 bash run-tests.sh # [unix and py311]
    - PIPENV_PYTHON=3.12 bash run-tests.sh # [unix and py312]
    - PIPENV_PYTHON=3.13 bash run-tests.sh # [unix and py313]
    - set PIPENV_PYTHON=3.9 && cmd /c run-tests.bat # [win and py39]
    - set PIPENV_PYTHON=3.10 && cmd /c run-tests.bat # [win and py310]
    - set PIPENV_PYTHON=3.11 && cmd /c run-tests.bat # [win and py311]
    - set PIPENV_PYTHON=3.12 && cmd /c run-tests.bat # [win and py312]
    - set PIPENV_PYTHON=3.13 && cmd /c run-tests.bat # [win and py313]

about:
  home: https://github.com/pypa/pipenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Development Workflow for Humans.
  description: |
    Pipenv is a tool that aims to bring the best of all packaging worlds (bundler, composer,
    npm, cargo, yarn, etc.) to the Python world.
  doc_url: https://pipenv.pypa.io
  dev_url: https://github.com/pypa/pipenv

extra:
  recipe-maintainers:
    - drewgilliam
    - roccqqck
